package com.sample
 
import javax.swing.JOptionPane;
import org.kie.api.runtime.KieRuntime
import javax.swing.JFrame
global JFrame frame
global javax.swing.JTextArea textArea

declare Question
	text: String
	response : String
end

declare Response
	text: String
end



rule "Init"
	dialect "java"
	when
	then
	Question q = new Question();
	q.setText("A cartoon based on a video game?");
	String res = gui.processQuestion(q.getText()); q.setResponse(res);
	insert(q);
end

rule "nintendo"
	when 
		Question (text == "A cartoon based on a video game?", response == "Yes")
	then
		Question q = new Question();
		q.setText("A nintendo franchise?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end


rule "nintendo_finish"
	when 
		Question (text == "A nintendo franchise?", response == "Yes")
	then
		String response = "1. The Super Mario Bros. Super Show\n2. Captain N The Game Master\n3. The Adventures of Super Mario Bros. 3\n4. Super Mario World\n5. The Legend of Zelda\n6. Pokemon";
		gui.showResult(response);
end

rule "non_nintendo_finish"
	when 
		Question (text == "A nintendo franchise?", response == "No")
	then
		String response = "1. Adventures of Sonic the Hedgehog\n2. Mega Man\n3. Mortal Kombat Defenders of the Realm\n4. Double Dragon\n5. Wing Commander Academy\n6. Street Fighter";
		gui.showResult(response);
end

rule "celebrity"
	when 
		Question (text == "A cartoon based on a video game?", response == "No")
	then
		Question q = new Question();
		q.setText("A celebrity?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "celebrity_finish"
	when 
		Question (text == "A celebrity?", response == "Yes")
	then
		String response = "1. Chuck Norris: Karate Kommandos\n2. Mister T";
		gui.showResult(response);
end

rule "animals_furries"
	when 
		Question (text == "A celebrity?", response == "No")
	then
		Question q = new Question();
		q.setText("Animals, furries, and the like?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end


rule "cats"
	when 
		Question (text == "Animals, furries, and the like?", response == "Yes")
	then
		Question q = new Question();
		q.setText("Cats?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "cats_finish"
	when 
		Question (text == "Cats?", response == "Yes")
	then
		String response = "1. ThunderCats\n2. Swat Kats";
		gui.showResult(response);
end

rule "rodents"
	when 
		Question (text == "Cats?", response == "No")
	then
		Question q = new Question();
		q.setText("Rodents?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "rodents_finish"
	when 
		Question (text == "Rodents?", response == "Yes")
	then
		String response = "1. Biker Mice from Mars\n2. Danger Mouse\n3. Chip N Dale Rescue Rangers";
		gui.showResult(response);
end

rule "dinosaurs"
	when 
		Question (text == "Rodents?", response == "No")
	then
		Question q = new Question();
		q.setText("Dinosaurs?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "dinosaurs_finish"
	when 
		Question (text == "Dinosaurs?", response == "Yes")
	then
		String response = "1. Cadillacs and Dinosaurs\n2. Extreme Dinosaurs\n3. Dino Riders\n4. Dinosaucers";
		gui.showResult(response);
end

rule "ducks"
	when 
		Question (text == "Dinosaurs?", response == "No")
	then
		Question q = new Question();
		q.setText("Ducks?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "ducks_finish"
	when 
		Question (text == "Ducks?", response == "Yes")
	then
		String response = "1. Count Duckula\n2. DuckTales\n3. Darwing Duck";
		gui.showResult(response);
end

rule "bears"
	when 
		Question (text == "Ducks?", response == "No")
	then
		Question q = new Question();
		q.setText("Bears?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "bears_finish"
	when 
		Question (text == "Bears?", response == "Yes")
	then
		String response = "1. TaleSpin\n2. Disney's Adventures of the Gummi Bears\n3. The Care Bears";
		gui.showResult(response);
end

rule "monkeys"
	when 
		Question (text == "Bears?", response == "No")
	then
		Question q = new Question();
		q.setText("Monkeys?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "monkeys_finish"
	when 
		Question (text == "Monkeys?", response == "Yes")
	then
		String response = "Captain Simian and the Space Monkeys";
		gui.showResult(response);
end

rule "cows"
	when 
		Question (text == "Monkeys?", response == "No")
	then
		Question q = new Question();
		q.setText("Cows?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "cows_finish"
	when 
		Question (text == "Cows?", response == "Yes")
	then
		String response = "Wild West Cowboyts of Moo Mesa";
		gui.showResult(response);
end

rule "godless"
	when 
		Question (text == "Cows?", response == "No")
	then
		Question q = new Question();
		q.setText("Godless abominations?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "godless_finish_yes"
	when 
		Question (text == "Godless abominations?", response == "Yes")
	then
		String response = "1. Smurfs\n2. Snorks";
		gui.showResult(response);
end

rule "godless_finish_no"
	when 
		Question (text == "Godless abominations?", response == "No")
	then
		String response = "1. Teenage Mutant Ninja Turtles\n2. Street Sharks\n3. Gargoyles";
		gui.showResult(response);
end

rule "non_animals_furries"
	when Question (text == "Animals, furries, and the like?", response =="No")
	then 
		Question q = new Question();
		q.setText("Do you dig giant robots?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "giant_robots_finish"
	when Question(text =="Do you dig giant robots?", response == "Yes")
	then
		String response = "1. Robotech\n2. Voltron\n3. Tranformers\n4. Challenge of the Gobots";
		gui.showResult(response);
end

rule "non_giant_robots"
when Question(text =="Do you dig giant robots?", response == "No")
	then 
		Question q = new Question();
		q.setText("A cartoon based on a movie?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "movie"
when Question(text =="A cartoon based on a movie?", response == "Yes")
	then 
		Question q = new Question();
		q.setText("An R-rated movie?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end
rule "non_movie"
when Question(text =="A cartoon based on a movie?", response == "No")
	then 
		Question q = new Question();
		q.setText("Do you want a post-apocalyptic setting?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "r-rated"
when Question(text =="An R-rated movie?", response == "Yes")
	then 
		String response = "1. Rambo and the Force of Freedom\n2. Robocop: The Animated Series\n3. Highlander: The Animated Series";
		gui.showResult(response);
end

rule "non_r-rated"
when Question(text =="An R-rated movie?", response == "No")
	then 
		String response = "1. Star Wars: Ewoks\n2. Star Wars: Droids\n3. James Bond Jr.\n4. Extreme Ghostbusters\n5. The Real Ghostbusters";
		gui.showResult(response);
end

rule "apocalyptic"
when Question(text =="Do you want a post-apocalyptic setting?", response == "Yes")
	then 
		String response = "1. Highlander: The Animated Series\n2. Thundarr the Barbarian\n3. Cadilacs and Dinosaurus\n4. Spiral Zone";
		gui.showResult(response);
end

rule "non_apocalyptic"
when Question(text =="Do you want a post-apocalyptic setting?", response == "No")
	then 
		Question q = new Question();
		q.setText("Swords and sorcery?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "swords"
when Question(text =="Swords and sorcery?", response == "Yes")
	then 
		String response = "1. The Pirates of Dark Water\n2. Thundarr the Barbarian\n3. Visionaries\n4. Dungeons & Dragons\n5. She-Ra, Princess of Power\n6. Conan the Adventurer\n7. He-Man and the Masters of the Universe\n8. King Arthur and the Knights of Justice";
		gui.showResult(response);
end
rule "non_swords"
when Question(text =="Swords and sorcery?", response == "No")
	then 
		Question q = new Question();
		q.setText("Military and law enforcement?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "non_military"
when Question(text =="Military and law enforcement?", response == "No")
	then 
		Question q = new Question();
		q.setText("Space?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "military"
when Question(text =="Military and law enforcement?", response == "Yes")
	then 
		String response = "1. C.O.P.S.\n2. G.I. Joe\n3. M.A.S.K.\n4. Spiral Zone\n5. Exosquad\n6. SilverHawks\n7. Centurions\n8. Sky Commanders\n9. Sam & Max: Freelance Police\n10. The Adventure of the Galaxy Rangers\n11. Inspector Gadget\n12. Brave Starr";
		gui.showResult(response);
end
rule "non_space"
when Question(text =="Space?", response == "No")
	then 
		Question q = new Question();
		q.setText("Cowboys?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end
rule "space"
when Question(text =="Space?", response == "Yes")
	then 
		String response = "1. Captains Simian and the Space Monkeys\n2. Jayce and the Wheeled Warriors\n3. Exoscquad\n4. SilverHawks\n5. Sky Commanders\n6. The Adventure of the Galaxy Rangers\n7. BraveStarr";
		gui.showResult(response);
end
rule "cowboys"
when Question(text =="Cowboys?", response == "Yes")
	then 
		String response = "1. The Adventures of the Galaxy Rangers\n2. BraveStarr\n3. Wild West Cowboys of Moo Mesa";
		gui.showResult(response);
end 
rule "non_cowboys"
when Question(text =="Cowboys?", response == "No")
	then 
		Question q = new Question();
		q.setText("Do you want to understand what's going on?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "non_understand"
when Question(text =="Do you want to understand what's going on?", response == "No")
	then 
		Question q = new Question();
		q.setText("In an awesome way?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end
rule "non_awesome"
when Question(text =="In an awesome way?", response == "No")
	then 
		String response = "1.Aeon Flux";
		gui.showResult(response);
end

rule "awesome"
when Question(text =="In an awesome way?", response == "Yes")
	then 
		String response = "1. Inhumanoids";
		gui.showResult(response);
end

rule "understand"
when Question(text =="Do you want to understand what's going on?", response == "Yes")
	then 
		Question q = new Question();
		q.setText("Kids doing awesome stuff?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end
rule "kids"
when Question(text =="Kids doing awesome stuff?", response == "Yes")
	then 
		Question q = new Question();
		q.setText("In an educational manner?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end

rule "non_kids"
when Question(text =="Kids doing awesome stuff?", response == "No")
	then 
		Question q = new Question();
		q.setText("Do you like computers?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end


rule "computers"
when Question(text =="Do you like computers?", response == "Yes")
	then 
		String response = "1. ReBoot";
		gui.showResult(response);
end

rule "non_computers"
when Question(text =="Do you like computers?", response == "No")
	then 
		Question q = new Question();
		q.setText("Something truly outrageous?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end
rule "truly"
when Question(text =="Something truly outrageous?", response == "No")
	then 
		Question q = new Question();
		q.setText("The undead?");
		String res = gui.processQuestion(q.getText()); 
		q.setResponse(res);
		insert(q);
end
rule "non_truly"
when Question(text =="Something truly outrageous?", response == "Yes")
	then 
		String response = "1. Jem";
		gui.showResult(response);
end
rule "undead"
when Question(text =="The undead?", response == "Yes")
	then 
		String response = "1. Mummies Alive\n2. Skeleton Warriors";
		gui.showResult(response);
end

rule "non_undead"
when Question(text =="The undead?", response == "Yes")
	then 
		String response = "1. The World of David the Gnome";
		gui.showResult(response);
end

rule "educational"
when Question(text =="In an educational manner?", response == "Yes")
	then 
		String response = "1. The Magic School Bus\n2. Captain Planet and the Planeteers";
		gui.showResult(response);
end

rule "non_educational"
when Question(text =="In an educational manner?", response == "No")
	then 
		String response = "1. Mighty Max\n2. The Real Adventures of Jonny Quest\n3. Bionic Six";
		gui.showResult(response);
end