package com.sample
 
import javax.swing.JOptionPane;
import org.kie.api.runtime.KieRuntime
import javax.swing.JFrame
global JFrame frame
global javax.swing.JTextArea textArea

declare Question
	text: String
	response : String
end

declare Response
	text: String
end

function void processQuestion(JFrame frame, KieRuntime krt, Question q) {
        Object[] options = {"Yes",
                            "No"};

        int n = JOptionPane.showOptionDialog(frame,
                                             q.getText(),
                                             "",
                                             JOptionPane.YES_NO_OPTION,
                                             JOptionPane.QUESTION_MESSAGE,
                                             null,
                                             options,
                                             options[0]);

        q.setResponse(options[n].toString());
}

function void showResult(JFrame frame, KieRuntime krt, Question q) {
        JOptionPane.showMessageDialog(frame, q.getText(), "Here is your result:", JOptionPane.PLAIN_MESSAGE);  
}

rule "Init"
	dialect "java"
	when
	then
	Question q = new Question();
	q.setText("A cartoon based on a video game?");
	processQuestion(frame, kcontext.getKieRuntime(), q);
	insert(q);
end

rule "nintendo"
	when 
		q : Question (text == "A cartoon based on a video game?", response == "Yes")
	then
		q.setText("A nintendo franchise?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end


rule "nintendo_finish"
	when 
		q : Question (text == "A nintendo franchise?", response == "Yes")
	then
		String response = "1. The Super Mario Bros. Super Show\n2. Captain N The Game Master\n3. The Adventures of Super Mario Bros. 3\n4. Super Mario World\n5. The Legend of Zelda\n6. Pokemon";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "non_nintendo_finish"
	when 
		q : Question (text == "A nintendo franchise?", response == "No")
	then
		String response = "1. Adventures of Sonic the Hedgehog\n2. Mega Man\n3. Mortal Kombat Defenders of the Realm\n4. Double Dragon\n5. Wing Commander Academy\n6. Street Fighter";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "celebrity"
	when 
		q : Question (text == "A cartoon based on a video game?", response == "No")
	then
		q.setText("A celebrity?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "celebrity_finish"
	when 
		q : Question (text == "A celebrity?", response == "Yes")
	then
		String response = "1. Chuck Norris: Karate Kommandos\n2. Mister T";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "animals_furries"
	when 
		q : Question (text == "A celebrity?", response == "No")
	then
		q.setText("Animals, furries, and the like?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end


rule "cats"
	when 
		q : Question (text == "Animals, furries, and the like?", response == "Yes")
	then
		q.setText("Cats?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "cats_finish"
	when 
		q : Question (text == "Cats?", response == "Yes")
	then
		String response = "1. ThunderCats\n2. Swat Kats";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "rodents"
	when 
		q : Question (text == "Cats?", response == "No")
	then
		q.setText("Rodents?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "rodents_finish"
	when 
		q : Question (text == "Rodents?", response == "Yes")
	then
		String response = "1. Biker Mice from Mars\n2. Danger Mouse\n3. Chip N Dale Rescue Rangers";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "dinosaurs"
	when 
		q : Question (text == "Rodents?", response == "No")
	then
		q.setText("Dinosaurs?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "dinosaurs_finish"
	when 
		q : Question (text == "Dinosaurs?", response == "Yes")
	then
		String response = "1. Cadillacs and Dinosaurs\n2. Extreme Dinosaurs\n3. Dino Riders\n4. Dinosaucers";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "ducks"
	when 
		q : Question (text == "Dinosaurs?", response == "No")
	then
		q.setText("Ducks?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "ducks_finish"
	when 
		q : Question (text == "Ducks?", response == "Yes")
	then
		String response = "1. Count Duckula\n2. DuckTales\n3. Darwing Duck";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "bears"
	when 
		q : Question (text == "Ducks?", response == "No")
	then
		q.setText("Bears?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "bears_finish"
	when 
		q : Question (text == "Bears?", response == "Yes")
	then
		String response = "1. TaleSpin\n2. Disney's Adventures of the Gummi Bears\n3. The Care Bears";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "monkeys"
	when 
		q : Question (text == "Bears?", response == "No")
	then
		q.setText("Monkeys?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "monkeys_finish"
	when 
		q : Question (text == "Monkeys?", response == "Yes")
	then
		String response = "Captain Simian and the Space Monkeys";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "cows"
	when 
		q : Question (text == "Monkeys?", response == "No")
	then
		q.setText("Cows?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "cows_finish"
	when 
		q : Question (text == "Cows?", response == "Yes")
	then
		String response = "Wild West Cowboyts of Moo Mesa";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "godless"
	when 
		q : Question (text == "Cows?", response == "No")
	then
		q.setText("Godless abominations?");
		processQuestion(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "godless_finish_yes"
	when 
		q : Question (text == "Godless abominations?", response == "Yes")
	then
		String response = "1. Smurfs\n2. Snorks";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end

rule "godless_finish_no"
	when 
		q : Question (text == "Godless abominations?", response == "No")
	then
		String response = "1. Teenage Mutant Ninja Turtles\n2. Street Sharks\n3. Gargoyles";
		q.setText(response);
		showResult(frame, kcontext.getKieRuntime(), q);
		update(q);
end


